version: '3.8'

services:
  angular:
    image: angular
    ports:
      - "80:4200"
    volumes:
      - ./src:/usr/src/app/src
      - ./angular.json:/usr/src/app/angular.json
      - ./public:/usr/src/app/public
    command: 
      ng serve --host 0.0.0.0