version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:80"
    networks:
      - dev-network
    volumes:
      - ./backend:/var/www/html
      - ./backend/static/uploads:/var/www/html/static/uploads
      - ./backend/static/cache:/var/www/html/static/cache
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=lexisnexis
      - MYSQL_USER=lexisuser
      - MYSQL_PASSWORD=lexispass
      - MYSQL_ROOT_PASSWORD=lexisroot
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "4200:4200"
    networks:
      - dev-network
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/angular.json:/usr/src/app/angular.json
      - ./frontend/public:/usr/src/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_API_URL=http://localhost:8080
    depends_on:
      - backend

  db:
    image: mysql:8.3
    restart: always
    networks:
      - dev-network
    environment:
      MYSQL_DATABASE: lexisnexis
      MYSQL_USER: lexisuser
      MYSQL_PASSWORD: lexispass
      MYSQL_ROOT_PASSWORD: lexisroot
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql

volumes:
  db_data_dev:

networks:
  dev-network:
    driver: bridge