# Build Angular app
FROM node:22 AS build
WORKDIR /app
COPY frontend/ /app
RUN npm install -g @angular/cli
RUN npm install && npm run build

# Serve with NGINX
FROM nginx

Run rm -rf /usr/share/nginx/html/*
COPY misc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/*/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]